[package]
name = "payjoin_ffi"
version = "0.18.0"
license = "MIT OR Apache-2.0"
edition = "2021"
exclude = ["tests"]

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "payjoin_ffi"

[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.28.0", features = ["bindgen-tests"] }
bdk = { version = "0.29.0", features = ["all-keys", "use-esplora-ureq", "keys-bip39"] }
bitcoincore-rpc = "0.19.0"
[dependencies]

payjoin = {version = "=0.18.0",  features = ["send", "receive", "base64", "v2", "io"] }
uniffi = { version = "0.28.0" }
thiserror = "1.0.47"
ohttp = { version = "0.5.1" }
url = "2.5.0"
base64 = "0.22.1"
hex = "0.4.3"


[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
strip = true


[features]
default = ["uniffi/cli"]
uniffi=[]
